api/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage  
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :
"""
from django.conf.urls import url, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'role', RoleViewSet)
router.register(r'userrole', UserRoleViewSet)
router.register(r'questioninfo', QuestionInfoViewSet)
router.register(r'optioninfo', OptionInfoViewSet)
router.register(r'examinationinfo', ExaminationInfoViewSet)
router.register(r'examinationinfoquestioninfoprofile', ExaminationInfoQuestionInfoProfileViewSet)

app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),
]

project_manage/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('question_manage/', include('question_manage.urls'), name='question_manage'),  # 问题管理
    path('accounts/', include('accounts.urls'), name='accounts'),  # 用户管理
    path('', include('project_page.urls')),  # 主页
    path('system_manager/', include('system_manager.urls')),  # 后台管理
    path('exam_online/', include('exam_online.urls')),  # 在线考试
    path('api/', include('api.urls')),  # api 预留
    url(r'mdeditor/', include('mdeditor.urls')),  # Markdown专用
    url(r'^api-auth/', include('rest_framework.urls')),  # api 专用
    url(r'^work_diary/', include('work_diary.urls')),  # api 专用
    path('password-reset/', include('password_reset.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_page/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   项目主页 Urls
"""
from django.urls import path
from . import views, utils_upload_img
app_name = "project_page"
urlpatterns = [
    path('', views.index, name='index'),
    path('get_menu/', views.get_menu, name='get_menu'),  # 获取菜单
    path('get_notice/', views.get_notice, name='get_notice'),  # 获取消息
    path('upload_img/', utils_upload_img.upload_img, name='upload_img'),  # 上传图片
    path('console/', views.console, name='console'),  # 控制台
    path('day_flash/', views.day_flash, name='day_flash'),  # 定期调用函数，统计每日已解决问题
    path('bulshit/', views.bulshit, name='bulshit')  # 写着玩的，v-182
]

question_manage/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   问题管理 Url
-- 准备好了么？这题可能有点难
"""
from django.urls import path
from . import views


app_name = "question_manage"
urlpatterns = [
    path('new_question/', views.new_question, name='new_question'),  # 新建问题
    path('question/', views.question, name='question'),  # 问题查看
    path('get_question/', views.get_question, name='get_question'),  # 获取问题(JSON)
    path('views_question/', views.views_question, name='views_question'),  # 显示问题具体内容
    path('solved_question/', views.solved_question, name='solved_question'),  # 已完结问题
    path('unresolved_question/', views.unresolved_question, name='unresolved_question'),  # 未完结问题
    path('change_user/', views.change_user, name='change_user'),  # 改变负责人
    path('team_question/', views.team_question, name='team_question'),
    path('get_team_question/', views.get_team_question, name='get_team_question'),
    # update_log
    path('update_log/', views.update_log, name='update_log'),  # 更新记录
    path('test/', views.test, name='test')  # 常驻 q-271
]

question_manage/models.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   models.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   问题管理 Models
"""
from django.db import models
from django.utils import timezone
from mdeditor.fields import MDTextField #必须导入
from accounts.models import Profile
from system_manager.models import Project, Mod

# Create your models here.


class Question(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(max_length=255, verbose_name="问题名")
    dept = models.CharField(max_length=255, null=True, verbose_name="部门")
    user = models.ForeignKey(Profile, blank=True, null=True, on_delete=models.SET_NULL, default=1)
    project = models.ForeignKey(Project, blank=True, null=True, on_delete=models.SET_NULL, default=1)
    mod = models.ForeignKey(Mod, blank=True, null=True, on_delete=models.SET_NULL, default=1)
    show = MDTextField()
    deptid = models.CharField(default=0, max_length=255, null=True, verbose_name='单位编码')
    indexno = models.CharField(default=0, max_length=255, null=True, verbose_name='指标号')
    docno = models.CharField(default=0, max_length=25, null=True, verbose_name='单据号')
    qname = models.CharField(default=0, max_length=255, null=True, verbose_name="姓名")
    qphone = models.CharField(default=0, max_length=255, null=True, verbose_name='电话')
    status = models.IntegerField(choices=((0, '待反馈'), (1, '待解决'), (2, '已解决')), default=0, verbose_name='状态')
    successinfo = models.CharField(null=True, max_length=255, verbose_name="完成信息")
    successtime = models.DateTimeField(null=True, verbose_name="完成时间")
    createtime = models.DateTimeField(default=timezone.now(), verbose_name="添加时间")

    class Meta:
        verbose_name = "问题"
        verbose_name_plural = verbose_name


class QuestionStatistics(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    new = models.IntegerField(default=0, verbose_name='新问题')
    solved = models.IntegerField(default=0, verbose_name='已解决问题')
    unresolved = models.IntegerField(default=0, verbose_name='待解决问题')
    createtime = models.DateTimeField(default=timezone.now(), verbose_name="添加时间")

question_manage/views.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   views.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   问题管理 Views
"""
from django.shortcuts import render, redirect, HttpResponse
from django.http.response import JsonResponse
from django.utils import timezone
from .models import Question
from .utils import Email
from django_redis import get_redis_connection
from system_manager.models import Mod, Project
from accounts.models import Profile
from django.contrib.auth.models import User, Group
import json
# Create your views here.
"""
dept: 部门
deptid: 部门ID
indexno: 指标号
docno: 单据号
qname: 姓名
qphone: 电话
user: 用户
mod: 模块
project: 项目
show: 内容
"""


def question(request):
    """
    url: /question_manage/question/
    问题信息
    :param request:
    :return:question.html
    """
    if Group.objects.get(user=request.user.id).id != 2:
        disabled = 'disabled'
    users = Profile.objects.all()
    mods = Mod.objects.all()
    projects = Project.objects.all()
    return render(request, 'question_manage/question.html', locals())


def solved_question(request):
    """
    url: /question_manage/solved_question/
    已解决问题
    :param request:
    :return:solved_question.html
    """

    mods = Mod.objects.all()
    projects = Project.objects.all()
    return render(request, 'question_manage/solved_question.html', locals())


def unresolved_question(request):
    """
    url: /question_manage/unresolved_question/
    待解决问题
    :param request:
    :return:default-unresolved_question.html  |  Json-status
    """
    if request.POST:
        # 解决问题
        try:
            successinfo = request.POST.get('successinfo', '')
            id = request.POST.get('id', '')
            # 更新状态
            Question.objects.filter(id=id).update(successinfo=successinfo, status=2, successtime=timezone.now())
            question_name =Question.objects.get(id=id)
            # url = request.META['HTTP_HOST']  # 获取当前url
            # email = Email(request.user.email)
            # email.send_question_over(question_name.name, request.user.name, id, successinfo, url)  # 发送邮件
            return JsonResponse({'status': True})
        except:
            return JsonResponse({'msg': '未知错误'})

    users = Profile.objects.all()
    mods = Mod.objects.all()
    projects = Project.objects.all()
    return render(request, 'question_manage/unresolved_question.html', locals())


def get_question(request):
    """
    url: /question_manage/solved_question/
    获取问题
    :param request:
    :return:Json-问题-List
    """
    question_results = []
    # 按名字搜索
    data = {}
    user = request.user.id
    if Group.objects.get(user=user).id != 2:
        data['user'] = user

    name = request.GET.get('name', '')
    if name:
        data['name__contains'] = name

    userin = request.GET.get('user', '')
    if userin and userin != '0':
        data['user'] = userin

    mod = request.GET.get('mod', '')
    if mod and mod != '0':
        data['mod'] = mod

    project = request.GET.get('project', '')
    if project and project != '0':
        data['project'] = project

    status = request.GET.get('status', '')
    if status and status != '1':
        data['status'] = status

    deptid = request.GET.get('deptid', '')
    if deptid:
        data['deptid__contains'] = deptid

    indexno = request.GET.get('indexno', '')
    if indexno:
        data['indexno__contains'] = indexno

    docno = request.GET.get('docno', '')
    if docno:
        data['docno__contains'] = docno

    qname = request.GET.get('qname', '')
    if qname:
        data['qname__contains'] = qname

    qphone = request.GET.get('qphone', '')
    if qphone:
        data['qphone__contains'] = qphone


    questions = Question.objects.filter(**data).all()
    # 分页控制
    page = request.GET.get('page', '')
    limit = request.GET.get('limit', '')
    page = int(page)
    limit = int(limit)
    min_page = page * limit - limit
    max_page = page * limit
    for i in range(min_page, max_page):
        try:
            question_data = {'id': questions[i].id,
                             'name': questions[i].name,
                             'dept': questions[i].dept,
                             'project': questions[i].project.name,
                             'mod': questions[i].mod.name,
                             'deptid': questions[i].deptid,
                             'indexno': questions[i].indexno,
                             'docno': questions[i].docno,
                             'qname': questions[i].qname,
                             'qphone': questions[i].qphone,
                             'status': '待反馈' if questions[i].status == 0 else '已解决',
                             'createtime': questions[i].createtime}
            question_results.append(question_data)
        except:
            pass
    return JsonResponse({'code':0, 'data': question_results, 'count': len(questions)})


def new_question(request):
    """
    url: /question_manage/new_question/
    问题新建
    :param request:
    :return: default-new_question.html  |  Json-Status
    """
    if request.is_ajax():
        # 新建问题
        if request.POST:
            data = {}
            if request.POST['name']:
                name = request.POST['name']
            else:
                data['message'] = '请输入问题名！'
                return HttpResponse(json.dumps(data))
            try:
                dept = request.POST['dept']
                deptid = request.POST.get('deptid', '')
                indexno = request.POST.get('indexno', '')
                docno = request.POST.get('docno', '')
                qname = request.POST.get('qname', '')
                qphone = request.POST.get('qphone', '')
                user = request.POST['user']  # 无异常处理，若未填写则无返回
                mod = request.POST['mod']  # ...
                project = request.POST['project']  # ...
                show = request.POST['show']  # 无异常处理，若未填写则无返回
                project = Project.objects.get(id=project)
                mod = Mod.objects.get(id=mod)
                user = Profile.objects.get(username=user)
                x = Question(name=name, dept=dept, user=user,
                             project=project, mod=mod, show=show,
                             deptid=deptid, indexno=indexno, docno=docno,
                             qname=qname, qphone=qphone, createtime=timezone.now())
                x.save()
            except:
                data['message'] = '问题创建失败！请联系管理员解决！'
                return HttpResponse(json.dumps(data))
            try:
                conn = get_redis_connection('default')
                conn.sadd(request.POST['user'], x.id)
            except:
                data['message'] = '问题已创建成功，但Redis访问出现错误！'
                return HttpResponse(json.dumps(data))
            # try:
            #     url = request.META['HTTP_HOST']
            #     email = Email(user.email)
            #     email.send_new_question(name, user.name, x.id, url)  # 发送邮件
            # except:
            #     data['message'] = '问题已创建成功，但Email发送出现错误！'
            #     return HttpResponse(json.dumps(data))
            data['status'] = 1
            return HttpResponse(json.dumps(data))
    users = Profile.objects.all()
    mods = Mod.objects.all()
    projects = Project.objects.all()
    # 你现在的生活也许不是你想要的，但绝对是你自找的!  / 271?214?136?height?=?  | result < 1300/
    return render(request, 'question_manage/new_question.html', locals())


def views_question(request):
    """
    url: /question_manage/views_question/
    问题内容展示
    :param request:
    :return: views_question.html
    """
    id = request.GET.get('questionId', '')
    try:
        conn = get_redis_connection('default')
        conn.srem(request.user.username, id)  # 问题已查看从redis内删除
    except:
        pass
    question = Question.objects.get(id=int(id))
    return render(request, 'question_manage/views_question.html', locals())


def change_user(request):
    """
    url: /question_manage/change_user/
    :param request:
    :return: Json-Status
    """
    question_id = request.POST.get('id', '')
    change_user_id = request.POST.get('userid', '')
    user = request.user
    user_group = Group.objects.get(user=user).id
    if Question.objects.filter(id=question_id, user=user) is not None or user_group == 2:
        Question.objects.filter(id=question_id).update(user_id=change_user_id)
        return JsonResponse({'status': '0'})
    else:
        return JsonResponse({'msg': '禁止越权访问'})


def team_question(request):
    """
    url: /question_manage/team_question/
    团队进度
    :param request:
    :return:team_question.html
    """
    return render(request, 'question_manage/team_question.html', locals())


def get_team_question(request):
    """

    :param request:
    :return:
    """
    users = Profile.objects.all()
    cur_time = timezone.datetime.now()
    day_num = cur_time.isoweekday()
    week_day = (cur_time - timezone.timedelta(days=day_num))
    team_question_result = []
    for user in users:
        reusult = {'id': str(user.id),
                   'name': str(user.name),
                   'allquestionlen': len(Question.objects.filter(user=user.id).all()),
                   'unresolvedlen': len(Question.objects.filter(status=0, user=user.id).all()),
                   'solved': len(Question.objects.filter(status=2, user=user.id).all()),
                   'weekquestionlen': len(Question.objects.filter(createtime__range=(week_day, cur_time),
                                                                    user=user.id).all()),
                   'monquestion': len(Question.objects.filter(createtime__month=cur_time.month, user=user.id).all()),
                   'dayquestion': len(Question.objects.filter(createtime__day=cur_time.day, user=user.id).all())}
        team_question_result.append(reusult)

templates/question_manage/team_question.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link href="/static/component/layui/css/layui.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/admin/css/pearForm.css" />
		<link href="/static/admin/css/pearCommon.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/admin/css/pearOper.css"/>
	</head>
	<body class="pear-container">
	<div class="layui-card">
	    <div class="layui-card-body">
	        <table id="role-table" lay-filter="role-table"></table>
	    </div>
	</div>
	</body>
	
	<script type="text/html" id="role-bar">
	    <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="views"><i class="layui-icon layui-icon-circle-dot"></i></button>
	</script>


        <script type="text/html" id="createtime">
            {% verbatim myblock %}
            {{layui.util.toDateString(d.createtime, 'yyyy-MM-dd HH:mm:ss')}}
            {% endverbatim myblock %}
        </script>
		<script src="/static/component/layui/layui.js"></script>
		<script>
		    layui.use(['table','form','jquery'],function () {
		        let table = layui.table;
		        let form = layui.form;
		        let $ = layui.jquery;
		        var pearOper = layui.pearOper;
		        var pearTab = layui.pearTab;
		
		        let MODULE_PATH = "{% url 'question_manage:question' %}";
		
		        let cols = [
		            [
		                {type:'checkbox'},
		                {field:'id', title:'ID', width:80, fixed: 'left', unresize: true, totalRowText: '合计'},
		                {title: '姓名', field: 'name', align:'center', width:120},
		                {title: '问题总数', field: 'allquestionlen', align:'center', width:120},
		                {title: '待解决问题', field: 'unresolvedlen', align:'center', width:120},
		                {title: '已解决问题', field: 'solved', align:'center', width:120},
		                {title: '本月新增', field: 'monquestion', align:'center', width:120},
		                {title: '本周新增', field: 'weekquestionlen', align:'center', width:120},
		                {title: '本日新增', field: 'dayquestion', align:'center', width:120},
		            ]
		        ];
		
		        table.render({
		            elem: '#role-table',
		            url: '{% url 'question_manage:get_team_question' %}',
		            page: true ,
		            cols: cols ,
		            skin: 'line',
		            toolbar: '#role-toolbar',
		            defaultToolbar: [{
		                layEvent: 'refresh',
		                icon: 'layui-icon-refresh',
		            }, 'filter', 'print', 'exports']
		        });

		
		        table.on('toolbar(role-table)', function(obj){
		            if(obj.event === 'add'){
		                window.add();
		            } else if(obj.event === 'refresh'){
		                window.refresh();
		            } else if(obj.event === 'batchRemove'){
		                window.batchRemove(obj);
		            }
		        });
		
		        form.on('submit(role-query)', function(data){
		            table.reload('role-table',{where:data.field});
		            return false;
		        });
		
		        form.on('switch(role-enable)', function(obj){
		            layer.tips(this.value + ' ' + this.name + '：'+ obj.elem.checked, obj.othis);
		        });


		
		        window.refresh = function(){
		            table.reload('role-table');
		        }
		    })
		</script>
	</body>
</html>

templates/question_manage/unresolved_question.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link href="/static/component/layui/css/layui.css" rel="stylesheet" />
		<link href="/static/admin/css/pearCommon.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/admin/css/pearOper.css"/>
	</head>
	<body class="pear-container">
	<div class="layui-card">
	    <div class="layui-card-body">
	        <form class="layui-form" action="">
	            <div class="layui-form-item">
	                <label class="layui-form-label">问题名</label>
	                <div class="layui-input-inline">
	                    <input type="text" name="name" placeholder="" class="layui-input">
	                </div>
	                <label class="layui-form-label">所属模块</label>
                    <div class="layui-input-inline layui-row layui-col-space10 layui-col-md4"  lay-filter="component-form-element">
                      <select name="mod" lay-verify="required" lay-search id="mod">
                      <option value="0">请选择</option>
                      {% for mod in mods %}
                          <option value="{{ mod.id }}">{{ mod.name }}</option>
                      {% endfor %}
                      </select>
                    </div>
	                <label class="layui-form-label">所属项目</label>
                    <div class="layui-input-inline layui-row layui-col-space10 layui-col-md4"  lay-filter="component-form-element">
                      <select name="project" lay-verify="required" lay-search id="project">
                      <option value="0">请选择</option>
                      {% for project in projects %}
                          <option value="{{ project.id }}">{{ project.name }}</option>
                      {% endfor %}
                      </select>
                    </div>
                    <label class="layui-form-label">单位编码</label>
	                <div class="layui-input-inline">
	                    <input type="text" name="deptid" placeholder="" class="layui-input">
	                </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">指标号</label>
	                <div class="layui-input-inline">
	                    <input type="text" name="indexno" placeholder="" class="layui-input">
	                </div>
                    <label class="layui-form-label">单据号</label>
	                <div class="layui-input-inline">
	                    <input type="text" name="docno" placeholder="" class="layui-input">
	                </div>
                    <label class="layui-form-label">姓名</label>
	                <div class="layui-input-inline">
	                    <input type="text" name="qname" placeholder="" class="layui-input">
	                </div>
                    <label class="layui-form-label">电话</label>
	                <div class="layui-input-inline">
	                    <input type="text" name="qphone" placeholder="" class="layui-input">
	                </div>
                    </div>
	                <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="role-query">
	                    <i class="layui-icon layui-icon-search"></i>
	                    查询
	                </button>
	                <button type="reset" class="pear-btn pear-btn-md">
	                    <i class="layui-icon layui-icon-refresh"></i>
	                    重置
	                </button>
	            </div>
	        </form>
	    </div>
	</div>
	<div class="layui-card">
	    <div class="layui-card-body">
	        <table id="role-table" lay-filter="role-table"></table>
	    </div>
	</div>
	</body>
	
{#	<script type="text/html" id="role-toolbar">#}
{#	    <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">#}
{#	        <i class="layui-icon layui-icon-add-1"></i>#}
{#	        新增#}
{#	    </button>#}
{#	</script>#}
    <script type="text/html" id="createtime">
        {% verbatim myblock %}
        {{layui.util.toDateString(d.createtime, 'yyyy-MM-dd HH:mm:ss')}}
        {% endverbatim myblock %}
    </script>
	<script type="text/html" id="role-bar">
	    <button class="pear-btn pear-btn-success pear-btn-sm" lay-event="success"><i class="layui-icon layui-icon-ok-circle"></i></button>
	    <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="views"><i class="layui-icon layui-icon-circle-dot"></i></button>
	    <button class="pear-btn pear-btn-sm" lay-event="change"><i class="layui-icon layui-icon-flag"></i></button>
	</script>


		
		<script src="/static/component/layui/layui.js"></script>
		<script>
		    layui.use(['table','form','jquery'],function () {
		        let table = layui.table;
		        let form = layui.form;
		        let $ = layui.jquery;
		        var pearOper = layui.pearOper;
		        var pearTab = layui.pearTab;
		
		        let MODULE_PATH = "{% url 'question_manage:question' %}";
		
		        let cols = [
		            [
		                {type:'checkbox'},
		                {field:'id', title:'ID', width:80, unresize: true, totalRowText: '合计'},
		                {title: '问题名', field: 'name', align:'center', width:120},
		                {title: '部门', field: 'dept', align:'center', width:120},
		                {title: '所属项目', field: 'project', align:'center', width:120},
		                {title: '所属模块', field: 'mod', align:'center', width:120},
		                {title: '单位编码', field: 'deptid', align:'center', width:120},
		                {title: '指标号', field: 'indexno', align:'center', width:120},
		                {title: '单据号', field: 'docno', align:'center', width:120},
		                {title: '姓名', field: 'qname', align:'center', width:120},
		                {title: '电话', field: 'qphone', align:'center', width:120},
		                {title: '添加时间', field: 'createtime', align:'center',templet:'#createtime', sort: true, width:200},
		                {fixed: 'right', title: '操作', toolbar: '#role-bar', align:'center', width:150}
		            ]
		        ];
		
		        table.render({
		            elem: '#role-table',
		            url: '{% url 'question_manage:get_question' %}'+'?status=0',
		            page: true ,
		            cols: cols ,
		            skin: 'line',
		            toolbar: '#role-toolbar',
		            defaultToolbar: [{
		                layEvent: 'refresh',
		                icon: 'layui-icon-refresh',
		            }, 'filter', 'print', 'exports']
		        });
		
		        table.on('tool(role-table)', function(obj){
		            if(obj.event === 'views'){
		                window.views(obj);
		            } else if(obj.event === 'success'){
		                window.success(obj);
		            } else if(obj.event === 'change'){
		                window.change(obj);
		            }
		        });
		
		        table.on('toolbar(role-table)', function(obj){
		            if(obj.event === 'add'){
		                window.add();
		            } else if(obj.event === 'refresh'){
		                window.refresh();
		            } else if(obj.event === 'batchRemove'){
		                window.batchRemove(obj);
		            }
		        });
		
		        form.on('submit(role-query)', function(data){
		            table.reload('role-table',{where:data.field})
		            return false;
		        });
		
		        form.on('switch(role-enable)', function(obj){
		            layer.tips(this.value + ' ' + this.name + '：'+ obj.elem.checked, obj.othis);
		        });
		
		        window.success = function(obj){
		            layer.open({
		                type: 1,
		                title: '任务完成',
                        area: ['500px', '300px'],
		                content: '<div style="padding: 20px;"><textarea class="layui-textarea" id="successinfo" placeholder="填写完成信息"></textarea>',
                        btn:['完成','取消'],
                        yes:function (index,layero) {
		                    layer.close(index);
		                    let loading = layer.load();
                            data = {
                                'id':obj.data['id'],
                                'successinfo':$("#successinfo").val(),
                            }
                            $.post("{% url 'question_manage:unresolved_question' %}",data,function(r){
                                layer.close(loading);
                                if(r.status){
                                    layer.msg('问题已完结！',{icon:1,time:1000},function(){
		                                obj.del()
		                            });
                                }else{
                                    layer.msg(r.msg);
                                }
                            })
                        }
		            });
		        };
		        window.change = function(obj){
		            layer.open({
		                type: 1,
		                title: '人员指派',
                        area: ['500px', '300px'],
		                content: $('#change-user'),
                        btn:['指派','取消'],
                        yes:function (index,layero) {
		                    objc = document.getElementsByName("user");
		                    check_val = [];
		                    for(k in objc){
                                if(objc[k].checked)
                                    check_val.push(objc[k].value)
		                    }
		                    layer.close(index);
		                    let loading = layer.load();
                            data = {
                                'id':obj.data['id'],
                                'userid': check_val[0],
                            };
                            $.post("{% url 'question_manage:change_user' %}",data,function(r){
                                layer.close(loading);
                                if(r.status){
                                    layer.msg("完成", {
                                        icon: 1,
                                        time: 1000
                                    }, function () {
                                        obj.del();
                                    });
                                }else{
                                    layer.msg(r.msg, {
                                        icon: 2,
                                        time: 1000
                                    })
                                }
                            })
                        }
		            });
		        };
		
		        window.views = function(obj){
                    layer.open({
		                type: 2,
		                title: obj.data['name'],
		                shade: 0.1,
		                area: ['1000px', '500px'],
		                content: '{% url 'question_manage:views_question' %}'+'?questionId='+obj.data['id']
		            });
		        }

		
		        window.refresh = function(){
		            table.reload('role-table');
		        }
		    })
		</script>
    <div style="padding: 20px;display:none;" id="change-user">
        <div class="layui-card layui-form" lay-filter="component-form-element">
            <div class="layui-card-body layui-row layui-col-space10">
                <div class="layui-col-md12">
                    {% for user in users %}
                    <input type="radio" name="user" value="{{ user.id }}" title="{{ user.name }}">
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
	</body>
</html>