api/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage  
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :
"""
from django.conf.urls import url, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'role', RoleViewSet)
router.register(r'userrole', UserRoleViewSet)
router.register(r'questioninfo', QuestionInfoViewSet)
router.register(r'optioninfo', OptionInfoViewSet)
router.register(r'examinationinfo', ExaminationInfoViewSet)
router.register(r'examinationinfoquestioninfoprofile', ExaminationInfoQuestionInfoProfileViewSet)

app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),
]

exam_online/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-20 13:04
@Software       :   PyCharm
@Show           :   在线考试 Urls
"""
from django.urls import path
from . import views

app_name = "exam_online"
urlpatterns = [
    path('questioninfo_manage/', views.questioninfo_manage, name="questioninfo_manage"),  # 试题列表
    path('get_questioninfo/', views.get_questioninfo, name="get_questioninfo"),  # 获取试题信息
    path('new_questioninfo/', views.new_questioninfo, name="new_questioninfo"),  # 新建试题
    path('edit_questioninfo/', views.edit_questioninfo, name='edit_questioninfo'),  # 编辑试题 q-211
    path('exam/', views.exam, name='exam'),  # 考试
    path('exam_list/', views.exam_list, name='exam_list'),  # 参加过的考试
    path('get_exam/', views.get_exam, name='get_exam'),  # 获取考试信息
    path('get_exam_info/', views.get_exam_info, name='get_exam_info'),  # 获取考试信息
]

project_manage/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('question_manage/', include('question_manage.urls'), name='question_manage'),  # 问题管理
    path('accounts/', include('accounts.urls'), name='accounts'),  # 用户管理
    path('', include('project_page.urls')),  # 主页
    path('system_manager/', include('system_manager.urls')),  # 后台管理
    path('exam_online/', include('exam_online.urls')),  # 在线考试
    path('api/', include('api.urls')),  # api 预留
    url(r'mdeditor/', include('mdeditor.urls')),  # Markdown专用
    url(r'^api-auth/', include('rest_framework.urls')),  # api 专用
    url(r'^work_diary/', include('work_diary.urls')),  # api 专用
    path('password-reset/', include('password_reset.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

question_manage/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   问题管理 Url
-- 准备好了么？这题可能有点难
"""
from django.urls import path
from . import views


app_name = "question_manage"
urlpatterns = [
    path('new_question/', views.new_question, name='new_question'),  # 新建问题
    path('question/', views.question, name='question'),  # 问题查看
    path('get_question/', views.get_question, name='get_question'),  # 获取问题(JSON)
    path('views_question/', views.views_question, name='views_question'),  # 显示问题具体内容
    path('solved_question/', views.solved_question, name='solved_question'),  # 已完结问题
    path('unresolved_question/', views.unresolved_question, name='unresolved_question'),  # 未完结问题
    path('change_user/', views.change_user, name='change_user'),  # 改变负责人
    path('team_question/', views.team_question, name='team_question'),
    path('get_team_question/', views.get_team_question, name='get_team_question'),
    # update_log
    path('update_log/', views.update_log, name='update_log'),  # 更新记录
    path('test/', views.test, name='test')  # 常驻 q-271
]

system_manager/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   系统管理Urls
"""
from django.urls import path
from . import account_views, project_views

app_name = "system_manager"
urlpatterns = [
    # -------------------------------------------------------------------
    # account change
    # user
    path('get_user/', account_views.get_user, name='get_user'),
    path('user/', account_views.user, name="user"),
    path('user_edit/', account_views.user_edit, name='user_edit'),
    path('user_remove/', account_views.user_remove, name='user_remove'),
    path('add_user/', account_views.add_user, name='add_user'),
    # group
    path('group/', account_views.group, name='group'),
    path('get_group/', account_views.get_group, name='get_group'),
    path('remove_group/', account_views.remove_group, name='remove_group'),
    # role
    path('role/', account_views.role, name='role'),
    path('get_role/', account_views.get_role, name='get_role'),
    path('remove_role/', account_views.remove_role, name='remove_role'),
    path('role_menu/', account_views.role_menu, name='role_menu'),
    # -------------------------------------------------------------------
    # project change
    # project
    path('project/', project_views.project, name='project'),
    path('get_project/', project_views.get_project, name='get_project'),
    path('remove_project/', project_views.remove_project, name='remove_project'),
    path('add_project/', project_views.add_project, name='add_project'),
    path('edit_project/', project_views.edit_project, name='edit_project'),
    # mod
    path('mod/', project_views.mod, name='mod'),
    path('get_mod/', project_views.get_mod, name='get_mod'),
    path('remove_mod/', project_views.remove_mod, name='remove_mod'),
    # platform
    path('platform/', project_views.platform, name='platform'),
    path('get_platform/', project_views.get_platform, name='get_platform'),
    path('remove_platform/', project_views.remove_platform, name='remove_platform'),
    # menu
    path('menu/', project_views.menu, name='menu'),
    path('get_menu/', project_views.get_menu, name='get_menu'),
    path('remove_menu/', project_views.remove_menu, name='remove_menu'),
]

exam_online/models.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   models.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-20 13:04
@Software       :   PyCharm
@Show           :   在线考试 Models
"""
from django.db import models
from django.utils import timezone
from system_manager.models import Mod
from accounts.models import Profile
from django.contrib.auth.models import Group


# 试题信息
class QuestionInfo(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(max_length=500, default='', verbose_name='试题题目')
    mod = models.ForeignKey(Mod, on_delete=models.CASCADE, verbose_name='所属模块', default='')
    tq_type = models.IntegerField(
        choices=((0, '选择'), (1, '判断'), (2, '填空')), verbose_name='试题类型', default=0
    )
    type = models.IntegerField(
        choices=((0, '基础类'), (1, '业务类'), (2, '技术类'),
                 (3, '沟通类'), (4, '综合类'), (5, '其他')), verbose_name='类型', default=0
    )
    is_share = models.BooleanField(default=False, verbose_name='是否分享')
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='cuser', verbose_name='创建人')
    updated_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='uuser', verbose_name='更新人')
    create_time = models.DateTimeField(default=timezone.now, verbose_name='创建时间')
    updated_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    class Meta:
        verbose_name = '试题信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class OptionInfo(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    questioninfo = models.ForeignKey(QuestionInfo, on_delete=models.CASCADE, verbose_name='试题信息')
    option = models.IntegerField(choices=((0, 'A'), (1, 'B'),
                                          (2, 'C'), (3, 'D'),
                                          (4, 'E'), (5, 'F')), default=0, verbose_name='选项')
    option_content = models.CharField(max_length=255, default='', verbose_name='选项内容')
    is_right = models.BooleanField(default=True, verbose_name='是否为正确答案')
    create_time = models.DateTimeField(default=timezone.now, verbose_name='创建时间')

    class Meta:
        verbose_name = '试题选项信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.option_content


class ExaminationInfo(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(max_length=50, default='', verbose_name='考试名称')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='所属用户组')
    exam_type = models.IntegerField(choices=((0, '练习'), (1, '正式')), default=0, verbose_name='类型')
    create_user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='考试人')
    create_time = models.DateTimeField(default=timezone.now, verbose_name='创建时间')

    class Meta:
        verbose_name = '考试信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ExaminationInfoQuestionInfoProfile(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    examination = models.ForeignKey(ExaminationInfo, on_delete=models.CASCADE, verbose_name='考试信息')
    question = models.ForeignKey(QuestionInfo, on_delete=models.CASCADE, verbose_name='试题信息')
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='用户信息')
    input_content = models.CharField(max_length=5000, default='', verbose_name='考试名称')
    is_right = models.BooleanField(default=True, verbose_name='是否为正确')

    class Meta:
        verbose_name = '考试_试题_用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.input_content

templates/exam_online/edit_question.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="/static/component/layui/css/layui.css" />
    <link rel="stylesheet" href="/static/admin/css/pearCommon.css" />
	<link rel="stylesheet" href="/static/admin/css/pearForm.css" />
    <link rel="stylesheet" href="/static/admin/css/pearButton.css" />
    <link href="/static/editor.md/css/editormd.min.css" rel="stylesheet" />
  <style>
    body{margin: 10px;}


  </style>
</head>
<body class="layui-bg-gray">
  <div >
    <div class="layui-row layui-col-space15">
      <div class="layui-col-md12">
        <div class="layui-card">
          <div class="layui-card-body layui-row layui-form layui-col-space10" lay-filter="component-form-element">
			<div class="layui-col-md12">
			  <input type="text" name="name" hover value="{{ questioninfo.name }}" autocomplete="off" class="layui-input" id="name">
			</div>

            <div class="layui-card-body layui-row layui-col-space10 layui-col-md12">
              <select name="mod" lay-verify="required" lay-search id="mod">
              <option value="{{ questioninfo.mod.id }}">{{ questioninfo.mod.name }}</option>
              {% for mod in mods %}
                  <option value="{{ mod.id }}">{{ mod.name }}</option>
              {% endfor %}
              </select>
            </div>

            <div class="layui-card-body layui-row layui-col-space10 layui-col-md12">
              <select name="tq_type" lay-verify="required" lay-search id="tq_type">
                        <option value="{{ questioninfo.tq_type }}">{{ questioninfo.get_tq_type_display }}</option>
              {% for questioninfo_tq_type in questioninfo_tq_types %}
                  <option value="{{ questioninfo_tq_type.0 }}">{{ questioninfo_tq_type.1 }}</option>
              {% endfor %}
              </select>
            </div>

            <div class="layui-card-body layui-row layui-col-space10 layui-col-md12">
              <select name="type" lay-verify="required" lay-search id="type">
                        <option value="{{ questioninfo.type }}">{{ questioninfo.get_type_display }}</option>
              {% for questioninfo_type in questioninfo_types %}
                  <option value="{{ questioninfo_type.0 }}">{{ questioninfo_type.1 }}</option>
              {% endfor %}
              </select>
            </div>

            <div class="layui-card-body layui-row layui-col-space10 layui-col-md12">
              <select name="option" lay-verify="required" lay-search id="option">
                        <option value="{{ option_info_true.option }}">{{ option_info_true.get_option_display }}</option>
              {% for option in options %}
                  <option value="{{ option.0 }}">{{ option.1 }}</option>
              {% endfor %}
              </select>
            </div>
            {% for option_info in options_info%}
            <div class="layui-col-md6">
			  <input type="text" name="{{ option_info.option }}" hover value="{{ option_info.option_content }}" autocomplete="off" class="layui-input" id="{{ option_info.option }}">
			</div>
          {% endfor %}
              <div class="layui-col-md6">
                  <button class="layui-btn layui-btn-radius change" lay-submit lay-filter="component-form-element">立即提交</button>
              </div>
          </div>
        </div>

      </div>
    </div>
  </div>

<script src="/static/component/layui/layui.js"></script>
<script>
layui.use(['form', 'jquery'], function () {
    let form = layui.form;
    let $ = layui.jquery;

    $("body").on("click",".change",function(){
        let loading = layer.load();
        $.ajax({
            url:'{% url 'exam_online:edit_questioninfo' %}',
            type:'POST',
            data:{'questioninfo_id':{{ questioninfo.id }},
                  'name':$('#name').val(),
                  'mod':$('#mod').val(),
                  'tq_type':$('#tq_type').val(),
                  'type':$('#type').val(),
                  'option':$('#option').val(),
                  '0':$('#0').val(),
                  '1':$('#1').val(),
                  '2':$('#2').val(),
                  '3':$('#3').val(),
                  '4':$('#4').val(),
                  '5':$('#5').val(),},
            success:function(data){
                layer.close(loading);
                console.log(data);
                if(data['status']) {
                    layer.msg("完成", {
                        icon: 1,
                        time: 1000
                    }, function () {
                        parent.innerPageAddCallBack(parent.layer.getFrameIndex(window.name));
                    })
                }else{
                    layer.msg(data.msg);
                    console.log(data.msg)
                }
            }
        });
    });
});
</script>
</body>
</html>        

templates/exam_online/exam_list.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link href="/static/component/layui/css/layui.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/admin/css/pearForm.css" />
		<link href="/static/admin/css/pearCommon.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/admin/css/pearOper.css"/>
	</head>
	<body class="pear-container">
	<div class="layui-card">
	    <div class="layui-card-body">
	        <form class="layui-form" action="">
	            <div class="layui-form-item">
	                <label class="layui-form-label">考试名称</label>
	                <div class="layui-input-inline">
	                    <input type="text" id="name" name="name" placeholder="" class="layui-input">
	                </div>
                    <label class="layui-form-label">考试类型:</label>
                    <div class="layui-input-inline">
                        <select lay-verify="required" id="type" name="type">
                            <option value="0" selected>练习</option>
                            <option value="1">正式</option>
                        </select>
                    </div>
                    <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="role-query">
                        <i class="layui-icon layui-icon-search"></i>
                        查询
                    </button>
                    <button type="reset" class="pear-btn pear-btn-md">
                        <i class="layui-icon layui-icon-refresh"></i>
                        重置
                    </button>
                </div>

	        </form>
	    </div>
	</div>
	<div class="layui-card">
	    <div class="layui-card-body">
	        <table id="role-table" lay-filter="role-table"></table>
	    </div>
	</div>
	</body>
	
	<script type="text/html" id="role-bar">
	    <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="views"><i class="layui-icon layui-icon-circle-dot"></i></button>
	</script>


        <script type="text/html" id="createtime">
            {% verbatim myblock %}
            {{layui.util.toDateString(d.createtime, 'yyyy-MM-dd HH:mm:ss')}}
            {% endverbatim myblock %}
        </script>
        <script type="text/html" id="examtype">
            123
        </script>
		<script src="/static/component/layui/layui.js"></script>
		<script>
		    layui.use(['table','form','jquery'],function () {
		        let table = layui.table;
		        let form = layui.form;
		        let $ = layui.jquery;
		        var pearOper = layui.pearOper;
		        var pearTab = layui.pearTab;
		
		        let MODULE_PATH = "{% url 'question_manage:question' %}";
		
		        let cols = [
		            [
		                {type:'checkbox'},
		                {field:'id', title:'ID', width:80, fixed: 'left', unresize: true, totalRowText: '合计'},
		                {title: '考试名', field: 'name', align:'center'},
		                {title: '考试类型', field: 'exam_type', align:'center'},
		                {title: '考试时间', field: 'create_time', align:'center'},
                        {fixed: 'right', title: '操作', toolbar: '#role-bar', align:'center', width:80}
		            ]
		        ];
		
		        table.render({
		            elem: '#role-table',
		            url: '{% url 'exam_online:get_exam' %}',
		            page: true ,
		            cols: cols ,
		            skin: 'line',
		            toolbar: '#role-toolbar',
		            defaultToolbar: [{
		                layEvent: 'refresh',
		                icon: 'layui-icon-refresh',
		            }, 'filter', 'print', 'exports']
		        });
		
		        table.on('tool(role-table)', function(obj){
		            if(obj.event === 'views'){
		                window.views(obj);
		            } else if(obj.event === 'success'){
		                window.success(obj);
		            }
		        });
		
		        table.on('toolbar(role-table)', function(obj){
		            if(obj.event === 'add'){
		                window.add();
		            } else if(obj.event === 'refresh'){
		                window.refresh();
		            } else if(obj.event === 'batchRemove'){
		                window.batchRemove(obj);
		            }
		        });
		
		        form.on('submit(role-query)', function(data){
		            table.reload('role-table',{where:data.field});
		            return false;
		        });
		
		        form.on('switch(role-enable)', function(obj){
		            layer.tips(this.value + ' ' + this.name + '：'+ obj.elem.checked, obj.othis);
		        });

		
		        window.views = function(obj){
                    layer.open({
		                type: 2,
		                title: obj.data['name'],
		                shade: 0.1,
		                area: ['1000px', '500px'],
		                content: '{% url 'exam_online:get_exam_info' %}'+'?examid='+obj.data['id']
		            });
		        };

		
		        window.refresh = function(){
		            table.reload('role-table');
		        }
		    })
		</script>
	</body>
</html>

templates/exam_online/get_exam_info.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <title>RoleMenu</title>
	<link rel="stylesheet" href="/static/component/layui/css/layui.css" />
	<link rel="stylesheet" href="/static/admin/css/pearForm.css" />
  <style>
    body{margin: 10px;}


  </style>
</head>
<body class="layui-bg-gray">
  <div >
    <div class="layui-row layui-col-space15">
      <div class="layui-col-md12">
        <div class="layui-card layui-form" lay-filter="component-form-element">
          <div class="layui-card-header">考试结果</div>
          <div class="layui-card-body layui-row layui-col-space10">
                {% for exam_info in exam_infos %}
                    {% if exam_info.is_right is False %}
            <div class="layui-col-md9" style="color:red">{{ exam_info.question }}</div>
                    {% else %}
            <div class="layui-col-md9" style="color:green">{{ exam_info.question }}</div>
                    {% endif %}
            <div class="layui-col-md3">{{ exam_info.is_right }}</div>
                {% endfor %}
        </div>
      </div>
      </div>
    </div>
  </div>

<script src="/static/component/layui/layui.js"></script>

</body>
</html>

templates/exam_online/questioninfo_manage.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link href="/static/component/layui/css/layui.css" rel="stylesheet" />
		<link href="/static/admin/css/pearCommon.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/admin/css/pearOper.css"/>
	</head>
	<body class="pear-container">
	<div class="layui-card">
	    <div class="layui-card-body">
	        <form class="layui-form" action="">
	            <div class="layui-form-item">
	                <label class="layui-form-label">名称</label>
	                <div class="layui-input-inline">
	                    <input type="text" name="name" placeholder="" class="layui-input">
	                </div>
	                <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="role-query">
	                    <i class="layui-icon layui-icon-search"></i>
	                    查询
	                </button>
	                <button type="reset" class="pear-btn pear-btn-md">
	                    <i class="layui-icon layui-icon-refresh"></i>
	                    重置
	                </button>
	            </div>
	        </form>
	    </div>
	</div>
	<div class="layui-card">
	    <div class="layui-card-body">
	        <table id="role-table" lay-filter="role-table"></table>
	    </div>
	</div>
	</body>
	
	<script type="text/html" id="role-toolbar">
	    <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">
	        <i class="layui-icon layui-icon-add-1"></i>
	        新增
	    </button>
	</script>

	<script type="text/html" id="role-bar">
	    <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit"><i class="layui-icon layui-icon-edit"></i></button>
	    <button class="pear-btn pear-btn-danger pear-btn-sm" lay-event="remove"><i class="layui-icon layui-icon-delete"></i></button>
	</script>
	
{#	<script type="text/html" id="role-bar">#}
{#	    <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit"><i class="layui-icon layui-icon-edit"></i></button>#}
{#	    <button class="pear-btn pear-btn-danger pear-btn-sm" lay-event="remove"><i class="layui-icon layui-icon-delete"></i></button>#}
{#	</script>#}


        <script type="text/html" id="createtime">
            {% verbatim myblock %}
            {{layui.util.toDateString(d.createtime, 'yyyy-MM-dd HH:mm:ss')}}
            {% endverbatim myblock %}
        </script>
		<script src="/static/component/layui/layui.js"></script>
		<script>
		    layui.use(['table','form','jquery'],function () {
		        let table = layui.table;
		        let form = layui.form;
		        let $ = layui.jquery;
		        var pearOper = layui.pearOper;
		
		        let MODULE_PATH = "{% url 'system_manager:mod' %}";
		
		        let cols = [
		            [
		                {type:'checkbox'},
		                {title: 'id', field: 'id', align:'center', sort: true},
		                {title: '试题题目', field: 'name', align:'center'},
		                {title: '所属模块', field: 'mod', align:'center'},
		                {title: '试题类型', field: 'type', align:'center', sort: true},
		                {title: '创建人', field: 'user', align:'center'},
		                {title: '创建人', field: 'createtime', align:'center',templet:'#createtime', sort: true},
		                {title: '操作', toolbar: '#role-bar', align:'center'}
		            ]
		        ]
		
		        table.render({
		            elem: '#role-table',
		            url: '{% url 'exam_online:get_questioninfo' %}',
		            page: true ,
		            cols: cols ,
		            skin: 'line',
		            toolbar: '#role-toolbar',
		            defaultToolbar: [{
		                layEvent: 'refresh',
		                icon: 'layui-icon-refresh', 
		            }, 'filter', 'print', 'exports']
		        });
		
		        table.on('tool(role-table)', function(obj){
		            if(obj.event === 'remove'){
		                window.remove(obj);
		            } else if(obj.event === 'edit'){
		                window.edit(obj);
		            }
		        });
		
		        table.on('toolbar(role-table)', function(obj){
		            if(obj.event === 'add'){
		                window.add();
		            } else if(obj.event === 'refresh'){
		                window.refresh();
		            } else if(obj.event === 'batchRemove'){
		                window.batchRemove(obj);
		            }
		        });
		
		        form.on('submit(role-query)', function(data){
		            table.reload('role-table',{where:data.field})
		            return false;
		        });
		
		        form.on('switch(role-enable)', function(obj){
		            layer.tips(this.value + ' ' + this.name + '：'+ obj.elem.checked, obj.othis);
		        });
		
		        window.add = function(){
		            layer.open({
		                type: 2,
                        shade: 0.1,
		                title: '新增',
                        area: ['1000px', '500px'],
                        content: '{% url 'exam_online:new_questioninfo' %}'
		            });
		        };

		
		        window.edit = function(obj){
		            layer.open({
		                type: 2,
                        shade: 0.1,
		                title: obj.data['name'] + '修改',
                        area: ['1000px', '500px'],
                        content: '{% url 'exam_online:edit_questioninfo' %}' + '?id=' + obj.data['id']
		            });
		        };
                window.innerPageAddCallBack = function(index){
                    console.log("innerPageAddCallBack:do anything...");
                    layer.close(index); //关闭弹窗
                    table.reload("task-table");//table重新加载
                }
		        window.remove = function(obj){
		            layer.confirm('确定要删除该用户组', {icon: 3, title:'提示'}, function(index){
		                layer.close(index);
		                let loading = layer.load();
		                $.ajax({
		                    url: '{% url 'system_manager:remove_mod' %}'+'?modid='+obj.data['id'],
		                    dataType:'json',
		                    type:'delete',
		                    success:function(result){
		                        layer.close(loading);
		                        if(result.success){
		                            layer.msg(result.msg,{icon:1,time:1000},function(){
		                                obj.del();
		                            });
		                        }else{
		                            layer.msg(result.msg,{icon:2,time:1000});
		                        }
		                    }
		                })
		            });
		        }

		
		        window.refresh = function(){
		            table.reload('role-table');
		        }
		    })
		</script>
	</body>
</html>