accounts/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   用户 Urls
-- 第一题开始喽，各位小伙伴们，锻炼一下自己的逻辑思维能力吧！
-- accounts, exam_online, project_page, question_manage, system_manager, templates
"""
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.sign_up, name="register"),  # 用户注册
    path('logout/', views.sign_out, name="logout"),  # 用户登出
    path('login/', views.sign_in, name='login'),  # 用户登录
    path('edit_userinfo/', views.edit_userinfo, name='edit_userinfo')  # 编辑用户信息 q-153
]

api/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage  
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :
"""
from django.conf.urls import url, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'role', RoleViewSet)
router.register(r'userrole', UserRoleViewSet)
router.register(r'questioninfo', QuestionInfoViewSet)
router.register(r'optioninfo', OptionInfoViewSet)
router.register(r'examinationinfo', ExaminationInfoViewSet)
router.register(r'examinationinfoquestioninfoprofile', ExaminationInfoQuestionInfoProfileViewSet)

app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),
]

project_manage/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('question_manage/', include('question_manage.urls'), name='question_manage'),  # 问题管理
    path('accounts/', include('accounts.urls'), name='accounts'),  # 用户管理
    path('', include('project_page.urls')),  # 主页
    path('system_manager/', include('system_manager.urls')),  # 后台管理
    path('exam_online/', include('exam_online.urls')),  # 在线考试
    path('api/', include('api.urls')),  # api 预留
    url(r'mdeditor/', include('mdeditor.urls')),  # Markdown专用
    url(r'^api-auth/', include('rest_framework.urls')),  # api 专用
    url(r'^work_diary/', include('work_diary.urls')),  # api 专用
    path('password-reset/', include('password_reset.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_page/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   项目主页 Urls
"""
from django.urls import path
from . import views, utils_upload_img
app_name = "project_page"
urlpatterns = [
    path('', views.index, name='index'),
    path('get_menu/', views.get_menu, name='get_menu'),  # 获取菜单
    path('get_notice/', views.get_notice, name='get_notice'),  # 获取消息
    path('upload_img/', utils_upload_img.upload_img, name='upload_img'),  # 上传图片
    path('console/', views.console, name='console'),  # 控制台
    path('day_flash/', views.day_flash, name='day_flash'),  # 定期调用函数，统计每日已解决问题
    path('bulshit/', views.bulshit, name='bulshit')  # 写着玩的，v-182
]

question_manage/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   问题管理 Url
-- 准备好了么？这题可能有点难
"""
from django.urls import path
from . import views


app_name = "question_manage"
urlpatterns = [
    path('new_question/', views.new_question, name='new_question'),  # 新建问题
    path('question/', views.question, name='question'),  # 问题查看
    path('get_question/', views.get_question, name='get_question'),  # 获取问题(JSON)
    path('views_question/', views.views_question, name='views_question'),  # 显示问题具体内容
    path('solved_question/', views.solved_question, name='solved_question'),  # 已完结问题
    path('unresolved_question/', views.unresolved_question, name='unresolved_question'),  # 未完结问题
    path('change_user/', views.change_user, name='change_user'),  # 改变负责人
    path('team_question/', views.team_question, name='team_question'),
    path('get_team_question/', views.get_team_question, name='get_team_question'),
    # update_log
    path('update_log/', views.update_log, name='update_log'),  # 更新记录
    path('test/', views.test, name='test')  # 常驻 q-271
]

work_diary/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   工作日记 Url
"""

from django.urls import path
from . import views


app_name = "work_diary"
urlpatterns = [
    path('new_diary/', views.new_diary, name='new_diary'),  # 新建问题
    path('my_diary/', views.my_diary, name='my_diary'),  # 问题查看
    path('get_diary/', views.get_diary, name='get_diary'),  # 获取问题(JSON)
    path('view_diary/', views.view_diary, name='view_diary'),  # 显示问题具体内容
    path('receive_diary/', views.receive_diary, name='receive_diary'),  # 已完结问题
]

templates/base.html
{% block content %}{% endblock content %}

templates/console.html
<html>
	<head>
		<meta charset="utf-8">
		<title>首页三</title>
		<meta name="renderer" content="webkit">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link rel="stylesheet" href="/static/component/layui/css/layui.css" media="all">
        <style>
			.top-panel {
				border-radius: 4px;
				text-align: center;
			}

			.top-panel>.layui-card-body {
				height: 60px;
			}

			.top-panel-number {
				line-height: 60px;
				font-size: 30px;
				border-right: 1px solid #eceff9;
			}

			.top-panel-tips {
				padding-left: 8px;
				padding-top: 16px;
				line-height: 30px;
				font-size: 12px
			}

			.pear-container {
				background-color: whitesmoke;
				margin: 10px;
			}

			.card {
				width: 100%;
				height: 160px;
				background-color: whitesmoke;
				border-radius: 4px;
			}

			.card .header .avatar {
				width: 28px;
				height: 28px;
				margin: 20px;
				border-radius: 50px;
			}

			.card .header {
				color: dimgray;
			}

			.card .body {
				color: gray;
			}

			.card .body {
				margin-left: 20px;
				margin-right: 20px;
			}

			.card .footer {
				margin-left: 20px;
				margin-right: 20px;
				margin-top: 20px;
				font-size: 13px;
				color: gray;
				position: absolute;
			}
			
			.list .list-item{
			       height: 33px;
				   line-height: 33px;
				   color: gray;
				   padding: 5px;
				   padding-left: 15px;
				   border-radius: 4px;
				   margin-top: 5.2px;
			}
			
			.custom-tab .layui-tab-title{
			       border-bottom-width: 0px; 
			       border-bottom-style: none;
			}
			.custom-tab .layui-tab-title li{
		      	   margin-left: 10px;
			}
			
			.list .list-item:hover{
				background-color: whitesmoke;
			}
			
			
			.list .list-item .title{
				font-size:13px;
				width: 100%;
			}
			.list .list-item .footer{
				position: absolute;
				right: 30px;
				font-size: 12px;
			}
			
			.top-panel-tips i {
			
				font-size: 33px;
			}
		
		</style>
	</head>
	<body class="pear-container">
		<div>
            <div class="layui-row layui-col-space10">
				<div class="layui-col-xs6 layui-col-md2">
                    <div class="layui-card top-panel">
						<div class="layui-card-header">问题总数</div>
						<div class="layui-card-body top-panel-number">
                            {{ all_question | length }}
						</div>
					</div>
                </div>
				<div class="layui-col-xs6 layui-col-md2">
                    <div class="layui-card top-panel">
						<div class="layui-card-header">待解决问题</div>
						<div class="layui-card-body top-panel-number">
                            {{ unresolved | length }}
						</div>
					</div>
                </div>
				<div class="layui-col-xs6 layui-col-md2">
                    <div class="layui-card top-panel">
						<div class="layui-card-header">已解决问题</div>
						<div class="layui-card-body top-panel-number">
                            {{ solved | length }}
						</div>
					</div>
                </div>
				<div class="layui-col-xs6 layui-col-md2">
                    <div class="layui-card top-panel">
						<div class="layui-card-header">本月新增</div>
						<div class="layui-card-body top-panel-number">
                            {{ mon_question | length }}
						</div>
					</div>
                </div>
				<div class="layui-col-xs6 layui-col-md2">
                    <div class="layui-card top-panel">
						<div class="layui-card-header">本周新增</div>
						<div class="layui-card-body top-panel-number">
                            {{ week_question | length }}
						</div>
					</div>
                </div>
				<div class="layui-col-xs6 layui-col-md2">
                    <div class="layui-card top-panel">
						<div class="layui-card-header">本日新增</div>
						<div class="layui-card-body top-panel-number">
                            {{ day_question | length }}
						</div>
					</div>
                </div>
			</div>
			<div class="layui-row layui-col-space10">
				<div class="layui-col-md9">
					<div class="layui-card">
						<div class="layui-card-body">
							<div class="layui-tab custom-tab layui-tab-brief" lay-filter="docDemoTabBrief">
							    <div id="echarts-records" style="background-color:#ffffff;min-height:400px;padding: 10px"></div>
							</div>   
						</div>
					</div>
				</div>
				<div class="layui-col-md3">
					<div class="layui-card">
						<div class="layui-card-header">最新问题</div>
						<div class="layui-card-body">
							<ul class="list">
                                {% for top_question in top_questions %}
								<li class="list-item"><span class="title">{{ top_question.name }}</span><span class="footer">{{ top_question.createtime | date:"Y-m-d H:i:s" }}</span></li>
                                {% endfor %}
						   </ul>
						</div>
					</div>
				</div>
			</div>
        </div>
		<!--</div>-->
		<script src="/static/component/layui/layui.js" charset="utf-8"></script>
		<script>
		    layui.use(['layer', 'echarts','element'], function () {
		        var $ = layui.jquery,
		            layer = layui.layer,
					element = layui.element,
		            echarts = layui.echarts;


		        var echartsRecords = echarts.init(document.getElementById('echarts-records'), 'walden');
		
		        var optionRecords = {
		            title: {
		                text: ''
		            },
		            tooltip: {
		                trigger: 'axis',
		                axisPointer: {
		                    type: 'cross',
		                    label: {
		                        backgroundColor: '#6a7985'
		                    }
		                }
		            },
		            legend: {
		                data: ['新增', '已解决', '待解决']
		            },
		            toolbox: {
		                feature: {
		                    saveAsImage: {}
		                }
		            },
		            grid: {
		                left: '3%',
		                right: '4%',
		                bottom: '3%',
		                containLabel: true
		            },
		            xAxis: [
		                {
		                    type: 'category',
		                    boundaryGap: false,
		                    data: ['周日', '周一', '周二', '周三', '周四', '周五', '周六']
		                }
		            ],
		            yAxis: [
		                {
		                    type: 'value'
		                }
		            ],
		            series: [
		                {
		                    name: '新增',
		                    type: 'line',
		                    stack: '总量',
		                    areaStyle: {},
		                    data: {{ new_tables }}
		                },
		                {
		                    name: '已解决',
		                    type: 'line',
		                    areaStyle: {},
		                    data: {{ solved_tables }}
		                },
		                {
		                    name: '待解决',
		                    type: 'line',
		                    stack: '总量',
		                    areaStyle: {},
		                    data: {{ unresolved_tables }}
		                },
		            ]
		        };
		        echartsRecords.setOption(optionRecords);

		        window.onresize = function () {
		            echartsRecords.resize();
		        }
		
		    });
		</script>
	</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<title>一体化系统问题跟踪管理系统</title>
	<head>

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link rel="stylesheet" href="/static/component/layui/css/layui.css" />
		<link rel="stylesheet" href="/static/admin/css/pearMenu.css" />
		<link rel="stylesheet" href="/static/admin/css/pearTab.css" />
		<link rel="stylesheet" href="/static/admin/css/pearTheme.css" />
		<link rel="stylesheet" href="/static/admin/css/pearLoad.css" />
		<link rel="stylesheet" href="/static/admin/css/pearFrame.css" />
		<link rel="stylesheet" href="/static/admin/css/pearAdmin.css" />
		<link rel="stylesheet" href="/static/admin/css/pearNotice.css" />
		<link rel="stylesheet" href="/static/admin/css/pearSocial.css" />
		<style id="pearone-bg-color"></style>
	</head>
	<body class="layui-layout-body  pear-admin">
		<!-- 布局框架 -->
		<div class="layui-layout layui-layout-admin">
			<div class="layui-header">
				<ul class="layui-nav layui-layout-left">
					<li class="collaspe layui-nav-item"><a href="#" class="layui-icon layui-icon-shrink-right"></a></li>
					<li class="refresh layui-nav-item"><a href="#" class="layui-icon layui-icon-refresh-1"></a></li>
				</ul>
				<div id="control" class="layui-layout-control"></div>
				<ul class="layui-nav layui-layout-right">
					<li class="layui-nav-item layui-hide-xs"><a href="#" class="fullScreen layui-icon layui-icon-screen-full"></a></li>
					<li class="layui-nav-item layui-hide-xs"><a href="{% url 'project_page:index' %}" class="layui-icon layui-icon-website"></a></li>
					<li class="layui-nav-item" id="headerNotice"></li>
                    {% if user.is_anonymous %}
                    <li class="layui-nav-item" lay-unselect="">
						<a href="javascript:;">用户</a>
						<dl class="layui-nav-child">
							<dd><a href="{% url 'accounts:login' %}">登录</a></dd>
							<dd><a href="{% url 'accounts:register' %}">注册</a></dd>
						</dl>
					</li>
                    {% else %}
					<li class="layui-nav-item" lay-unselect="">
						<a href="javascript:;">{{ user.name }}</a>
						<dl class="layui-nav-child">
							<dd><a href="javascript:;" class="pearson">个人信息</a></dd>
							<dd><a href="{% url 'accounts:logout' %}">注销登陆</a></dd>
						</dl>
					</li>
                    {% endif %}
{#					<li class="setting layui-nav-item"><a href="#" class="layui-icon layui-icon-more-vertical"></a></li>#}
				</ul>
			</div>
			<div class="layui-side layui-bg-black">
				<div class="layui-logo">
					<img class="logo" src="/static/admin/images/logo.png" />
					<span class="title">Project Manage</span>
				</div>
				<div class="layui-layer-content">
					<a href="http://beian.miit.gov.cn/">京ICP备2020034849号-1</a>
				</div>

				<div class="layui-side-scroll">
					<div id="sideMenu"></div>
				</div>
			</div>
			<div class="layui-body">
				<div id="content"></div>
			</div>
		</div>

        <!-- 遮 盖 层 -->
		<div class="pear-cover"></div>
        <!-- 加 载 动 画-->
		<div class="loader-main">
			<div class="loader"></div>
		</div>
        <!-- 收 缩 适 配 -->
		<div class="collaspe pe-collaspe layui-hide-sm">
			<i class="layui-icon layui-icon-shrink-right"></i>
		</div>
		<script src="/static/component/layui/layui.js"></script>
		<script>
			layui.use(['pearAdmin', 'jquery', 'pearTab', 'pearNotice'], function() {
				var pearAdmin = layui.pearAdmin;
				var $ = layui.jquery;
				var pearTab = layui.pearTab;
				var pearNotice = layui.pearNotice;

				var config = {
					keepLoad: false,
					muiltTab: true,
					control: false,
					theme: "dark-theme",
                {% if request.user.is_anonymous %}
					index: '{% url 'question_manage:new_question' %}',
                {% else %}
                    index: '{% url 'work_diary:new_diary' %}',
                {% endif %}
					data: '{% url 'project_page:get_menu' %}',
					done: function() {
					    /** 框架初始化 */
					}
				};
				
				pearAdmin.render(config);
				
				/**
				 * 消 息 初 始 化
				 * */
				pearNotice.render({
					elem: 'headerNotice',
					url: '{% url 'project_page:get_notice' %}',
					height: '200px',
					click: function(id, title) {
					    var randomid = Math.floor((Math.random()*1000000000000000)+10000000);
						pearTab.addTabOnlyByElem("content"
					,{id:randomid,title:title,url:"{% url 'question_manage:views_question' %}"+"?questionId="+id,close:true})
					}
				});

				$("body").on("click",".pearson",function(){
		            layer.open({
		                type: 1,
		                title: '{{ request.user.username }} 信息修改',
                        content: $('#edit-user-info-div'),
                        btn:['确认修改','取消'],
                        yes:function (index,layero) {
		                    let loading = layer.load();
                            data = {
                                'name':$("#name").val(),
                                'mobile':$("#mobile").val(),
                                'email':$("#email").val(),
                            };
                            $.post("{% url 'accounts:edit_userinfo' %}",data,function(r){
                                layer.close(loading);
                                if(r.status){
                                    layer.msg('修改成功');
                                    layer.close(index)
                                }else{
                                    layer.msg(r.msg);
                                }
                            })
                        }
		            });
				});

				$("ul").on("click",".new_question",function(){
					pearTab.addTabOnlyByElem("content"
					,{id:111,title:"新建问题",url:"{% url 'question_manage:new_question' %}",close:true})
				});

				$("li").on("click",".update_log",function(){
					pearTab.addTabOnlyByElem("content"
					,{id:99999,title:"项目管理平台更新记录",url:"{% url 'question_manage:update_log' %}",close:true})
				});

			})
		</script>
    <!-- 新建文集div块 -->
        <div style="padding: 20px;display:none;" id="edit-user-info-div">
            <div class="layui-form-item" style="margin-top:10px;">
            <label class="layui-form-label" style="text-align:left;padding:9px 0px;">姓名</label>
            <input class="layui-input" type="text" id="name" style="margin-bottom:10px;" value="{{ request.user.name }}" required  lay-verify="required">
            <label class="layui-form-label" style="text-align:left;padding:9px 0px;">电话号码</label>
            <input class="layui-input" type="text" id="mobile" style="margin-bottom:10px;" value="{{ request.user.moblie }}" required  lay-verify="required">
            <label class="layui-form-label" style="text-align:left;padding:9px 0px;">Email地址</label>
            <input class="layui-input" type="text" id="email" style="margin-bottom:10px;" value="{{ request.user.email }}" required  lay-verify="required">
            </div>
            <div style="color:red;font-size:12px;">*在可后台对用户权限进行进一步控制</div>
        </div>
	</body>
</html>

templates/message.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link rel="stylesheet" href="/static/component/layui/css/layui.css" />
	    <link rel="stylesheet" href="/static/component/notiflix/notiflix-2.0.0.css"/>
		<link rel="stylesheet" href="/static/admin/css/pearButton.css"/>
		<link rel="stylesheet" href="/static/admin/css/pearOper.css"/>
		<style>
	    	.pear-container{
	    		background-color: whitesmoke;
	    		margin: 10px;
	    	}
	    </style>
	</head>
	<body class="pear-container">
		
	
		<div class="layui-card">
			<div class="layui-card-header">消息提醒</div>
			<div class="layui-card-body">
				<div>
					<span>pearOper.Report("success","成功消息",msg)</span>
					<br>
					<br>
					<span>pearOper.Report("failure","错误消息",msg)</span>
					<br>
					<br>
					<span>pearOper.Report("warning","警告消息",msg)</span>
					<br>
					<br>
					<span>pearOper.Report("info","详情消息",msg)</span>
					<br>
					<br>
				</div>
			
				<button class="report-info pear-btn pear-btn-primary">通用消息</button>&nbsp;&nbsp;
				<button class="report-success pear-btn pear-btn-success">成功消息</button>&nbsp;&nbsp;
				<button class="report-failure pear-btn pear-btn-danger">错误消息</button>&nbsp;&nbsp;
				<button class="report-warning pear-btn pear-btn-warming">警告消息</button>&nbsp;&nbsp;
				
			</div>
		</div>
		
		<div class="layui-card">
			<div class="layui-card-header">消息提醒</div>
			<div class="layui-card-body">
				<div>
					<span>pearOper.msg("success","成功消息",msg)</span>
					<br>
					<br>
					<span>pearOper.msg("failure","错误消息",msg)</span>
					<br>
					<br>
					<span>pearOper.msg("warning","警告消息",msg)</span>
					<br>
					<br>
					<span>pearOper.msg("info","详情消息",msg)</span>
					<br>
					<br>
				</div>
			
				<button class="notice-info pear-btn pear-btn-primary">通用消息</button>&nbsp;&nbsp;
				<button class="notice-success pear-btn pear-btn-success">成功消息</button>&nbsp;&nbsp;
				<button class="notice-failure pear-btn pear-btn-danger">错误消息</button>&nbsp;&nbsp;
				<button class="notice-warning pear-btn pear-btn-warming">警告消息</button>&nbsp;&nbsp;
				
			</div>
		</div>
	  
		<div class="layui-card">
			<div class="layui-card-header">消息提醒</div>
			<div class="layui-card-body">
				
				<div>
					<br>
					<span>
						pearOper.confirm({ 
							title : 标题 ,
							message : 内容 ,
							success : 成功函数 ,
							cancle : 取消函数 
						})
					</span>
					<br>
					<br>
					
				</div>
			
				<button class="confirm pear-btn pear-btn-primary">通用消息</button>&nbsp;&nbsp;
				
			</div>
		</div>
		
		
		<div class="layer-right">
		
		</div>
	    
	   
		
		
		<script src="../../../component/layui/layui.js"></script>
	    <script>
			layui.use(['element','jquery','pearOper','code'],function(){
				var element = layui.element;
				var $ = layui.jquery;
				var pearOper = layui.pearOper;
				
				var msg = '"Do not try to become a person of success but try to become a person of value." <br><br>- Albert Einstein'
				
				$(".report-success").click(function(){
					
					pearOper.report({type:"success",title:"成功消息",message:msg});
				
				})
				
				$(".report-failure").click(function(){
					
					pearOper.report({type:"failure",title:"成功消息",message:msg});
				
				})
				
				$(".report-warning").click(function(){
					
					pearOper.report({type:"warning",title:"成功消息",message:msg});
				
				})
				
				$(".report-info").click(function(){
					
					pearOper.report({type:"info",title:"成功消息",message:msg});
				
				})
				
				$(".notice-success").click(function(){
					
					pearOper.notice({position:'right-top',type:"success",title:"成功消息"});
				
				})
				
				$(".notice-failure").click(function(){
					
					pearOper.notice({position:'right-top',type:"failure",title:"成功消息"});
				
				})
				
				$(".notice-warning").click(function(){
					
					pearOper.notice({position:'right-top',type:"warning",title:"成功消息"});
				
				})
				
				$(".notice-info").click(function(){
					
					pearOper.notice({position:'right-top',type:"info",title:"成功消息"});
				
				})
				
				$(".confirm").click(function(){
					
					
					pearOper.confirm({
						title:"确认框",
						message:msg,
						success:function(){
							console.log("确认")
						},
						cancle:function(){
							console.log("取消");
						}
					})
				})
				
			})
		</script>
	</body>
</html>

templates/new_question.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="/static/component/layui/css/layui.css" />
	<link rel="stylesheet" href="/static/admin/css/pearForm.css" />
    <link rel="stylesheet" href="/static/admin/css/pearButton.css" />
    <link href="/static/editor.md/css/editormd.min.css" rel="stylesheet" />
  <style>
    body{margin: 10px;}


  </style>
</head>
<body class="layui-bg-gray">
  <div >
    <div class="layui-row layui-col-space15">
      <div class="layui-col-md12">
        <div class="layui-card">
          <div class="layui-card-body layui-row layui-form layui-col-space10" lay-filter="component-form-element">
            <form action="{% url 'project_page:bulshit' %}" method="get">
                <div class="layui-col-md4">
                  <input type="text" name="title" hover placeholder="标题" autocomplete="off" class="layui-input" id="title">
                </div>
                <div class="layui-col-md4">
                  <input type="text" name="lenth" hover value="1000" placeholder="长度" autocomplete="off" class="layui-input" id="title">
                </div>
                  <div class="layui-col-md4">
                      <button class="layui-btn layui-btn-radius change" lay-submit value="Submit" lay-filter="component-form-element">立即提交</button>
                  </div>
            </form>

          </div>
        </div>
      <div class="layui-card">
          <p>{{ x | safe }}</p>
      </div>
      </div>
    </div>
  </div>

</body>
</html>        