api/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage  
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :
"""
from django.conf.urls import url, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'role', RoleViewSet)
router.register(r'userrole', UserRoleViewSet)
router.register(r'questioninfo', QuestionInfoViewSet)
router.register(r'optioninfo', OptionInfoViewSet)
router.register(r'examinationinfo', ExaminationInfoViewSet)
router.register(r'examinationinfoquestioninfoprofile', ExaminationInfoQuestionInfoProfileViewSet)

app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),
]

project_manage/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('question_manage/', include('question_manage.urls'), name='question_manage'),  # 问题管理
    path('accounts/', include('accounts.urls'), name='accounts'),  # 用户管理
    path('', include('project_page.urls')),  # 主页
    path('system_manager/', include('system_manager.urls')),  # 后台管理
    path('exam_online/', include('exam_online.urls')),  # 在线考试
    path('api/', include('api.urls')),  # api 预留
    url(r'mdeditor/', include('mdeditor.urls')),  # Markdown专用
    url(r'^api-auth/', include('rest_framework.urls')),  # api 专用
    url(r'^work_diary/', include('work_diary.urls')),  # api 专用
    path('password-reset/', include('password_reset.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_page/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   项目主页 Urls
"""
from django.urls import path
from . import views, utils_upload_img
app_name = "project_page"
urlpatterns = [
    path('', views.index, name='index'),
    path('get_menu/', views.get_menu, name='get_menu'),  # 获取菜单
    path('get_notice/', views.get_notice, name='get_notice'),  # 获取消息
    path('upload_img/', utils_upload_img.upload_img, name='upload_img'),  # 上传图片
    path('console/', views.console, name='console'),  # 控制台
    path('day_flash/', views.day_flash, name='day_flash'),  # 定期调用函数，统计每日已解决问题
    path('bulshit/', views.bulshit, name='bulshit')  # 写着玩的，v-182
]

work_diary/urls.py
# !/usr/anaconda3/bin python
# -*-coding:utf-8-*-
"""
@Project        :   project_manage
@FileName       :   urls.py
@Author         :   tangchaolizi
@Datetime       :   2020-06-16 13:04
@Software       :   PyCharm
@Show           :   工作日记 Url
"""

from django.urls import path
from . import views


app_name = "work_diary"
urlpatterns = [
    path('new_diary/', views.new_diary, name='new_diary'),  # 新建问题
    path('my_diary/', views.my_diary, name='my_diary'),  # 问题查看
    path('get_diary/', views.get_diary, name='get_diary'),  # 获取问题(JSON)
    path('view_diary/', views.view_diary, name='view_diary'),  # 显示问题具体内容
    path('receive_diary/', views.receive_diary, name='receive_diary'),  # 已完结问题
]

work_diary/models.py
from django.db import models
from django.utils import timezone
from mdeditor.fields import MDTextField
from accounts.models import Profile
from system_manager.models import Project

# Create your models here.


class diary(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    project = models.ForeignKey(Project, blank=True, null=True, on_delete=models.SET_NULL, default=1)
    show = MDTextField()
    status = models.IntegerField(choices=((0, '未读'), (1, '已读')), default=0, verbose_name='状态')
    create_user = models.ForeignKey(Profile, blank=True, null=True, on_delete=models.SET_NULL, default=1, related_name='create_user')
    receive_user = models.ForeignKey(Profile, blank=True, null=True, on_delete=models.SET_NULL, default=1, related_name='receive_user')
    create_time = models.DateTimeField(default=timezone.now(), verbose_name="添加时间")

    class Meta:
        verbose_name = "工作日记"
        verbose_name_plural = verbose_name

work_diary/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http.response import JsonResponse
from .models import diary
from django.utils import timezone
from accounts.models import Profile
from system_manager.models import Project
import json

# Create your views here.

def my_diary(request):
    """
    url: /question_manage/question/
    问题信息
    :param request:
    :return:question.html
    """
    users = Profile.objects.all()
    projects = Project.objects.all()
    return render(request, 'work_diary/my_diary.html', locals())


def receive_diary(request):
    """
    url: /question_manage/question/
    问题信息
    :param request:
    :return:question.html
    """
    users = Profile.objects.all()
    projects = Project.objects.all()
    return render(request, 'work_diary/receive_diary.html', locals())


def new_diary(request):
    """
    url: /question_manage/new_question/
    问题新建
    :param request:
    :return: default-new_question.html  |  Json-Status
    """
    if request.is_ajax():
        # 新建问题
        if request.POST:
            data = {}
            try:
                receive_user = request.POST['receive_user']  # 无异常处理，若未填写则无返回
                project = request.POST['project']  # ...
                show = request.POST['show']  # 无异常处理，若未填写则无返回
                project = Project.objects.get(id=project)
                receive_user = Profile.objects.get(username=receive_user)
                create_user = request.user
                x = diary(project=project, show=show, receive_user=receive_user, create_user=create_user,
                          create_time=timezone.now())
                x.save()
                data['status'] = 1
            except:
                data['message'] = '问题创建失败！请联系管理员解决！'
                return HttpResponse(json.dumps(data))
            return HttpResponse(json.dumps(data))
    users = Profile.objects.all()
    projects = Project.objects.all()
    return render(request, 'work_diary/new_diary.html', locals())


def get_diary(request):
    """
    url: /question_manage/solved_question/
    获取问题
    :param request:
    :return:Json-问题-List
    """
    diary_results = []
    # 按名字搜索
    data = {}
    if request.GET.get('type', '') == '1':
        data['receive_user'] = request.user.id
    else:
        data['create_user'] = request.user.id

    project = request.GET.get('project', '')
    if project and project != '0':
        data['project'] = project

    status = request.GET.get('status', '')
    if status and status != '2':
        data['status'] = status

    receive_user = request.GET.get('receiveuser', '')
    if receive_user and receive_user != '0':
        data['receive_user'] = receive_user

    create_user = request.GET.get('createuser', '')
    if create_user and create_user != '0':
        data['create_user'] = create_user

    diarys = diary.objects.filter(**data).all()
    # 分页控制
    page = request.GET.get('page', '')
    limit = request.GET.get('limit', '')
    page = int(page)
    limit = int(limit)
    min_page = page * limit - limit
    max_page = page * limit
    for i in range(min_page, max_page):
        try:
            diarys_data = {'id': diarys[i].id,
                           'project': diarys[i].project.name,
                           'status': '未读' if diarys[i].status == 0 else '已读',
                           'receiveuser': diarys[i].receive_user.name,
                           'createuser': diarys[i].create_user.name,
                           'createtime': diarys[i].create_time,}
            diary_results.append(diarys_data)
        except:
            pass
    return JsonResponse({'code':0, 'data': diary_results, 'count': len(diarys)})


def view_diary(request):
    """
    url: /question_manage/views_question/
    问题内容展示
    :param request:
    :return: views_question.html
    """
    id = request.GET.get('diaryId', '')
    diary_views = diary.objects.get(id=int(id))
    if request.user.id == diary_views.receive_user.id:
        diary_views.status = 1
        diary_views.save()
    return render(request, 'work_diary/views_diary.html', locals())

templates/work_diary/my_diary.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link href="/static/component/layui/css/layui.css" rel="stylesheet" />
		<link href="/static/admin/css/pearCommon.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/admin/css/pearOper.css"/>
	</head>
	<body class="pear-container">
	<div class="layui-card">
	    <div class="layui-card-body">
	        <form class="layui-form" action="">
	            <div class="layui-form-item">
	                <label class="layui-form-label">所属项目</label>
                    <div class="layui-input-inline layui-row layui-col-space10 layui-col-md4"  lay-filter="component-form-element">
                      <select name="project" lay-verify="required" lay-search id="project">
                      <option value="0">请选择</option>
                      {% for project in projects %}
                          <option value="{{ project.id }}">{{ project.name }}</option>
                      {% endfor %}
                      </select>
                    </div>
	                <label class="layui-form-label">接收用户</label>
                    <div class="layui-input-inline layui-row layui-col-space10 layui-col-md4"  lay-filter="component-form-element">
                      <select name="receiveuser" lay-verify="required" lay-search id="receiveuser">
                      <option value="0">请选择</option>
                      {% for user in users %}
                          <option value="{{ user.id }}">{{ user.name }}</option>
                      {% endfor %}
                      </select>
                    </div>
	                <label class="layui-form-label">接收人是否已读</label>
                    <div class="layui-input-inline layui-row layui-col-space10 layui-col-md4"  lay-filter="component-form-element">
                      <select name="status" lay-verify="required" lay-search id="status">
                      <option value="2">请选择</option>
                      <option value="0">未读</option>
                      <option value="1">已读</option>
                      </select>
                    </div>
	                <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="role-query">
	                    <i class="layui-icon layui-icon-search"></i>
	                    查询
	                </button>
	                <button type="reset" class="pear-btn pear-btn-md">
	                    <i class="layui-icon layui-icon-refresh"></i>
	                    重置
	                </button>
	            </div>
	            </div>
	        </form>
	    </div>
	</div>
	<div class="layui-card">
	    <div class="layui-card-body">
	        <table id="role-table" lay-filter="role-table"></table>
	    </div>
	</div>
	</body>
	
{#	<script type="text/html" id="role-toolbar">#}
{#	    <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">#}
{#	        <i class="layui-icon layui-icon-add-1"></i>#}
{#	        新增#}
{#	    </button>#}
{#	</script>#}
	
	<script type="text/html" id="role-bar">
	    <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="views"><i class="layui-icon layui-icon-circle-dot"></i></button>
	</script>


        <script type="text/html" id="createtime">
            {% verbatim myblock %}
            {{layui.util.toDateString(d.createtime, 'yyyy-MM-dd HH:mm:ss')}}
            {% endverbatim myblock %}
        </script>
		<script src="/static/component/layui/layui.js"></script>
		<script>
		    layui.use(['table','form','jquery'],function () {
		        let table = layui.table;
		        let form = layui.form;
		        let $ = layui.jquery;
		        var pearOper = layui.pearOper;
		        var pearTab = layui.pearTab;
		
		        let MODULE_PATH = "{% url 'work_diary:get_diary' %}";
		
		        let cols = [
		            [
		                {type:'checkbox'},
		                {field: 'id', title:'ID', width:80, fixed: 'left', unresize: true, totalRowText: '合计'},
		                {title: '所属项目', field: 'project', align:'center'},
		                {title: '接收人', field: 'receiveuser', align:'center'},
		                {title: '接收人是否已读', field: 'status', align:'center'},
		                {title: '添加时间', field: 'createtime', align:'center',templet:'#createtime', sort: true},
		                {fixed: 'right', title: '操作', toolbar: '#role-bar', align:'center'}
		            ]
		        ];
		
		        table.render({
		            elem: '#role-table',
		            url: '{% url 'work_diary:get_diary' %}',
		            page: true ,
		            cols: cols ,
		            skin: 'line',
		            toolbar: '#role-toolbar',
		            defaultToolbar: [{
		                layEvent: 'refresh',
		                icon: 'layui-icon-refresh',
		            }, 'filter', 'print', 'exports']
		        });
		
		        table.on('tool(role-table)', function(obj){
		            if(obj.event === 'views'){
		                window.views(obj);
		            } else if(obj.event === 'success'){
		                window.success(obj);
		            }
		        });
		
		        table.on('toolbar(role-table)', function(obj){
		            if(obj.event === 'add'){
		                window.add();
		            } else if(obj.event === 'refresh'){
		                window.refresh();
		            } else if(obj.event === 'batchRemove'){
		                window.batchRemove(obj);
		            }
		        });
		
		        form.on('submit(role-query)', function(data){
		            table.reload('role-table',{where:data.field})
		            return false;
		        });
		
		        form.on('switch(role-enable)', function(obj){
		            layer.tips(this.value + ' ' + this.name + '：'+ obj.elem.checked, obj.othis);
		        });

		
		        window.views = function(obj){
                    layer.open({
		                type: 2,
		                title: obj.data['name'],
		                shade: 0.1,
		                area: ['1000px', '500px'],
		                content: '{% url 'work_diary:view_diary' %}'+'?diaryId='+obj.data['id']
		            });
		        }

		
		        window.refresh = function(){
		            table.reload('role-table');
		        }
		    })
		</script>
	</body>
</html>

templates/work_diary/new_diary.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="/static/component/layui/css/layui.css" />
	<link rel="stylesheet" href="/static/admin/css/pearForm.css" />
    <link rel="stylesheet" href="/static/admin/css/pearButton.css" />
    <link href="/static/editor.md/css/editormd.min.css" rel="stylesheet" />
  <style>
    body{margin: 10px;}


  </style>
</head>
<body class="layui-bg-gray">
  <div >
    <div class="layui-row layui-col-space15">
      <div class="layui-col-md12">
        <div class="layui-card">
          <div class="layui-card-body layui-row layui-form layui-col-space10" lay-filter="component-form-element">
            <div class="layui-card-body layui-row layui-col-space10 layui-col-md6">
              <select name="receive_user" lay-verify="required" lay-search id="receive_user">
              <option value="0">请选择接收人</option>
              {% for user in users %}
                  <option value="{{ user.username }}">{{ user.name }}</option>
              {% endfor %}
              </select>
            </div>

            <div class="layui-card-body layui-row layui-col-space10 layui-col-md6">
              <select name="project" lay-verify="required" lay-search id="project">
                        <option value="0">请选择所属项目</option>
              {% for project in projects %}
                  <option value="{{ project.id }}">{{ project.name }}</option>
              {% endfor %}
              </select>
            </div>
              <div class="layui-col-md6">
                  <button class="layui-btn layui-btn-radius change" lay-submit lay-filter="component-form-element">立即提交</button>
              </div>
            <div id="test-editor">
                <textarea style="display:none;" id="show" name="show"></textarea>
            </div>
            <div class="layui-col-md4">
              <button class="layui-btn layui-btn-radius change" lay-submit lay-filter="component-form-element">立即提交</button>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

<script src="/static/component/layui/layui.js"></script>
<script>
layui.use(['form', 'element','jquery','pearOper','code'], function() {
    var from = layui.form;
    var element = layui.element;
    var $ = layui.jquery;
    var pearOper = layui.pearOper;

    $("body").on("click",".change",function(){
        let loading = layer.load();
        $.ajax({
            url:'{% url 'work_diary:new_diary' %}',
            type:'POST',
            data:{'receive_user':$('#receive_user').val(),
                  'project':$('#project').val(),
                  'show':$('#show').val(),},
            success:function(data){
                layer.close(loading);
                pearOper.loadRemove(1000);
                var dataObj=JSON.parse(data);
                if(dataObj['status']){
                    layer.msg('提交成功');
                }
                else{
                    layer.msg(dataObj.message)
                }
            }
        })
    })
})
</script>
<script src="/static/editor.md/jquery.min.js"></script>
<script src="/static/editor.md/editormd.min.js"></script>
<script type="text/javascript">
var testEditor;
testEditor = editormd("test-editor", {
     placeholder:'本条目支持使用Markdown语法编辑，左边编写，右边预览',  //默认显示的文字，这里就不解释了
     width: "90%",
     height: 640,
     syncScrolling: "single",
     path: "/static/editor.md/lib/",   //你的path路径（原资源文件中lib包在我们项目中所放的位置）
     saveHTMLToTextarea: true,
     emoji: true,
     taskList: true,
     tocm: true,         // Using [TOCM]
     tex: true,                   // 开启科学公式TeX语言支持，默认关闭
     flowChart: true,             // 开启流程图支持，默认关闭
     sequenceDiagram: true,       // 开启时序/序列图支持，默认关闭,
     imageUpload    : true, //开启图片上传
     imageFormats   : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
     imageUploadURL : "{% url 'project_page:upload_img' %}",
     toolbarIcons : function() {
         return [
             "undo", "redo", "|",
             "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
             "h1", "h2", "h3", "h4", "h5", "h6", "|",
             "list-ul", "list-ol", "hr", "|",
             "reference-link", "image", "code", "preformatted-text", "table", "datetime", "emoji", "html-entities", "|",
             "watch", "preview", "|",
             "help"
         ]
     },
});
</script>
</body>
</html>        

templates/work_diary/receive_diary.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link href="/static/component/layui/css/layui.css" rel="stylesheet" />
		<link href="/static/admin/css/pearCommon.css" rel="stylesheet" />
        <link rel="stylesheet" href="/static/admin/css/pearOper.css"/>
	</head>
	<body class="pear-container">
	<div class="layui-card">
	    <div class="layui-card-body">
	        <form class="layui-form" action="">
	            <div class="layui-form-item">
	                <label class="layui-form-label">所属项目</label>
                    <div class="layui-input-inline layui-row layui-col-space10 layui-col-md4"  lay-filter="component-form-element">
                      <select name="project" lay-verify="required" lay-search id="project">
                      <option value="0">请选择</option>
                      {% for project in projects %}
                          <option value="{{ project.id }}">{{ project.name }}</option>
                      {% endfor %}
                      </select>
                    </div>
	                <label class="layui-form-label">创建用户</label>
                    <div class="layui-input-inline layui-row layui-col-space10 layui-col-md4"  lay-filter="component-form-element">
                      <select name="createuser" lay-verify="required" lay-search id="createuser">
                      <option value="0">请选择</option>
                      {% for user in users %}
                          <option value="{{ user.id }}">{{ user.name }}</option>
                      {% endfor %}
                      </select>
                    </div>
	                <label class="layui-form-label">是否已读</label>
                    <div class="layui-input-inline layui-row layui-col-space10 layui-col-md6"  lay-filter="component-form-element">
                      <select name="status" lay-verify="required" lay-search id="status">
                      <option value="2">请选择</option>
                      <option value="0">未读</option>
                      <option value="1">已读</option>
                      </select>
                    </div>
	                <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="role-query">
	                    <i class="layui-icon layui-icon-search"></i>
	                    查询
	                </button>
	                <button type="reset" class="pear-btn pear-btn-md">
	                    <i class="layui-icon layui-icon-refresh"></i>
	                    重置
	                </button>
	            </div>
	            </div>
	        </form>
	    </div>
	</div>
	<div class="layui-card">
	    <div class="layui-card-body">
	        <table id="role-table" lay-filter="role-table"></table>
	    </div>
	</div>
	</body>
	
{#	<script type="text/html" id="role-toolbar">#}
{#	    <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">#}
{#	        <i class="layui-icon layui-icon-add-1"></i>#}
{#	        新增#}
{#	    </button>#}
{#	</script>#}
	
	<script type="text/html" id="role-bar">
	    <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="views"><i class="layui-icon layui-icon-circle-dot"></i></button>
	</script>


        <script type="text/html" id="createtime">
            {% verbatim myblock %}
            {{layui.util.toDateString(d.createtime, 'yyyy-MM-dd HH:mm:ss')}}
            {% endverbatim myblock %}
        </script>
		<script src="/static/component/layui/layui.js"></script>
		<script>
		    layui.use(['table','form','jquery'],function () {
		        let table = layui.table;
		        let form = layui.form;
		        let $ = layui.jquery;
		        var pearOper = layui.pearOper;
		        var pearTab = layui.pearTab;
		
		        let MODULE_PATH = "{% url 'work_diary:get_diary' %}";
		
		        let cols = [
		            [
		                {type:'checkbox'},
		                {field: 'id', title:'ID', width:80, fixed: 'left', unresize: true, totalRowText: '合计'},
		                {title: '所属项目', field: 'project', align:'center'},
		                {title: '创建人', field: 'createuser', align:'center'},
		                {title: '接收人是否已读', field: 'status', align:'center'},
		                {title: '添加时间', field: 'createtime', align:'center',templet:'#createtime', sort: true},
		                {fixed: 'right', title: '操作', toolbar: '#role-bar', align:'center'}
		            ]
		        ];
		
		        table.render({
		            elem: '#role-table',
		            url: '{% url 'work_diary:get_diary' %}' + '?type=1',
		            page: true ,
		            cols: cols ,
		            skin: 'line',
		            toolbar: '#role-toolbar',
		            defaultToolbar: [{
		                layEvent: 'refresh',
		                icon: 'layui-icon-refresh',
		            }, 'filter', 'print', 'exports']
		        });
		
		        table.on('tool(role-table)', function(obj){
		            if(obj.event === 'views'){
		                window.views(obj);
		            } else if(obj.event === 'success'){
		                window.success(obj);
		            }
		        });
		
		        table.on('toolbar(role-table)', function(obj){
		            if(obj.event === 'add'){
		                window.add();
		            } else if(obj.event === 'refresh'){
		                window.refresh();
		            } else if(obj.event === 'batchRemove'){
		                window.batchRemove(obj);
		            }
		        });
		
		        form.on('submit(role-query)', function(data){
		            table.reload('role-table',{where:data.field})
		            return false;
		        });
		
		        form.on('switch(role-enable)', function(obj){
		            layer.tips(this.value + ' ' + this.name + '：'+ obj.elem.checked, obj.othis);
		        });

		
		        window.views = function(obj){
                    layer.open({
		                type: 2,
		                title: obj.data['name'],
		                shade: 0.1,
		                area: ['1000px', '500px'],
		                content: '{% url 'work_diary:view_diary' %}'+'?diaryId='+obj.data['id']
		            });
		        }

		
		        window.refresh = function(){
		            table.reload('role-table');
		        }
		    })
		</script>
	</body>
</html>

templates/work_diary/views_diary.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="/static/component/layui/css/layui.css" />
	<link rel="stylesheet" href="/static/admin/css/pearForm.css" />
    <link rel="stylesheet" href="/static/admin/css/pearButton.css" />
    <link href="/static/editor.md/css/editormd.min.css" rel="stylesheet" />
  <style>
    body{margin: 10px;}


  </style>
</head>
<body class="layui-bg-gray">
  <div >
    <div class="layui-row layui-col-space15">
      <div class="layui-col-md12">
        <div class="layui-card">
          <div class="layui-card-body layui-row layui-form layui-col-space10" lay-filter="component-form-element">

            <div class="layui-card-body layui-row layui-col-space10 layui-col-md6">
              <select name="user" lay-verify="required" lay-search id="user" disabled>
                  <option value="1">{{ diary_views.receive_user.name }}</option>
              </select>
            </div>
            <div class="layui-card-body layui-row layui-col-space10 layui-col-md6">
              <select name="project" lay-verify="required" lay-search id="project" disabled>
                  <option value="1">{{ diary_views.project.name }}</option>
              </select>
            </div>
            <div id="test-editormd-view">
                <textarea style="display:none;">{{ diary_views.show }}</textarea>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

<script src="/static/component/layui/layui.js"></script>
<script>
layui.use(['form', 'element','jquery','pearOper','code'], function() {
    var from = layui.form;
    var element = layui.element;
    var $ = layui.jquery;
    var pearOper = layui.pearOper;
})
</script>
<script src="/static/editor.md/editormd.min.js"></script>
<script src="/static/editor.md/examples/js/jquery.min.js"></script>
<script src="/static/editor.md/lib/flowchart.min.js"></script>
<script src="/static/editor.md/lib/jquery.flowchart.min.js"></script>
<script src="/static/editor.md/lib/marked.min.js"></script>
<script src="/static/editor.md/lib/prettify.min.js"></script>
<script src="/static/editor.md/lib/raphael.min.js"></script>
<script src="/static/editor.md/lib/sequence-diagram.min.js"></script>
<script src="/static/editor.md/lib/underscore.min.js"></script>
<script src="/static/editor.md/editormd.min.js"></script>
<script type="text/javascript">
    var testEditor;
    $(function () {
        testEditor = editormd.markdownToHTML("test-editormd-view", {//注意：这里是上面DIV的id
            htmlDecode: "style,script,iframe",
            emoji: true,
            taskList: true,
            tex: true, // 默认不解析
            flowChart: true, // 默认不解析
            sequenceDiagram: true, // 默认不解析
            codeFold: true,
    });});
 </script>
</body>
</html>        